controllers/AuthController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\User;
use app\models\LoginForm;
use app\models\SignupForm;

class AuthController extends Controller {
	
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup() {
    	$signupForm = new SignupForm;
    	if (Yii::$app->request->isPost) {
    		$signupForm->load(Yii::$app->request->post());
    		if ($signupForm->signup()) {
                Yii::$app->session->setFlash('success', 'Check your email to finish your registration.');
                return $this->redirect(['site/index']);
            }		
    	}
    	return $this->render('signup', compact('signupForm'));
    }

    public function actionSignupConfirm($token) {
        if (empty($token)) {
            throw new \DomainException('Empty confirm token.');
        }

        $user = User::findOne(['email_confirm_token' => $token]);
        if (!$user) {
            throw new \DomainException('User is not found.');
        }
        $user->email_confirm_token = null;
        $user->save(false);

        if (!Yii::$app->getUser()->login($user)){
            throw new \RuntimeException('Error authentication.');
        }

        Yii::$app->session->setFlash('success', 'You have successfully confirmed your registration.');
        return $this->goHome();
    }
}

views/layouts/admin.php
<?php
  use app\assets\AppAsset;
  use yii\helpers\Url;
  use app\models\Category;

  AppAsset::register($this);
  $categories = Category::getAll();
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?=$this->title?></title>
        <?php $this->head() ?>
    </head>
    <body>
      <?php $this->beginBody() ?>
        <!--Header and navbar logo-->
        <header class="container-fluid mb-3 shadow">
            <nav class="navbar navbar-expand-md border navbar-light bg-primary row">
              <a class="navbar-brand" href="<?=Url::to(['site/index'])?>">My News Site</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="navbar-toggler-icon"></i>
              </button>
              <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link text-white" href="<?=Url::to(['/site/index'])?>">Home</a>
                  </li>
                  <?php if (Yii::$app->user->can('admin')):?>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/default/index'])?>">Admin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/article'])?>">Articles</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/user'])?>">Users</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/category'])?>">Categories</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/tag'])?>">Tags</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-white" href="<?=Url::to(['/admin/comment'])?>">Comments</a>
                    </li>
                  <?php endif;?>
                  <?php if (!Yii::$app->user->isGuest):?>
                    <li class="nav-item">
                      <a href="<?=Url::to(['/admin/user/view', 'id' => Yii::$app->user->id])?>" class="nav-link text-white">
                            <?='My Profile ('.Yii::$app->user->identity->name.')'?>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="<?=Url::to(['/auth/logout'])?>" class="nav-link text-white">
                            Logout
                      </a>
                    </li>
                  <?php endif;?>
                </ul>
              </div>
            </nav>
        </header>
        <div class="wrapper">
            <div class="container-fluid content">
                <?=$content?>
            </div>
            <!--Footer-->
            <footer class="container-fluid">
                <div class="row justify-content-center bg-secondary text-white text-center">
                    <ul class="col-md-4 list-group list-group-flush">
                      <li class="list-group-item bg-secondary">Contact us:</li>
                      <li class="list-group-item bg-secondary">
                        <a href="mailto:#" class="text-white">mysite@test.com</a>
                      </li>
                      <li class="list-group-item bg-secondary">
                        <a href="tel:#" class="text-white">000-000-000</a>
                        </li>
                    </ul>
                    <ul class="col-md-4 list-group list-group-flush">
                      <li class="list-group-item bg-secondary">Friends:</li>
                      <li class="list-group-item bg-secondary">
                        <a href="#" class="text-white">www.somesite.com</a>
                      </li>
                      <li class="list-group-item bg-secondary">
                        <a href="#" class="text-white">www.anothersite.com</a>
                      </li>
                    </ul>
                </div>
            </footer>
        </div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
  use app\assets\AppAsset;
  use yii\helpers\Url;
  use app\models\Category;

  AppAsset::register($this);
  $categories = Category::getAll();
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?=$this->title?></title>
        <?php $this->head() ?>
    </head>
    <body>
      <?php $this->beginBody() ?>
        <!--Header and navbar logo-->
        <header class="container-fluid mb-3 shadow">
            <nav class="navbar navbar-expand-sm border navbar-light bg-primary row">
              <a class="navbar-brand" href="<?=Url::to(['site/index'])?>">My News Site</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="navbar-toggler-icon"></i>
              </button>
              <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link text-white" href="<?=Url::to(['site/index'])?>">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <?php foreach ($categories as $category):?>
                        <a class="dropdown-item" href="<?=Url::to(['site/category', 'id' => $category->id])?>">
                          <?=$category->title?>
                          <div class="dropdown-divider"></div>
                        </a>
                      <?php endforeach;?>
                    </div>
                  </li>
                  <?php if (Yii::$app->user->can('admin')):?>
                    <li class="nav-item">
                      <a href="<?=Url::to(['admin/default/index'])?>" class="nav-link text-white">Admin</a>
                    </li>
                  <?php endif;?>
                  <?php if (Yii::$app->user->isGuest):?>
                    <li class="nav-item">
                      <a href="<?=Url::to(['auth/login'])?>" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-item">
                      <a href="<?=Url::to(['auth/signup'])?>" class="nav-link text-white">Register</a>
                    </li>
                  <?php else:?>
                    <li class="nav-item">
                      <a href="<?=Url::to(['/admin/user/view', 'id' => Yii::$app->user->id])?>" class="nav-link text-white">
                            <?='My Profile ('.Yii::$app->user->identity->name.')'?>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="<?=Url::to(['/auth/logout'])?>" class="nav-link text-white">
                            Logout
                      </a>
                    </li>
                  <?php endif;?>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="<?=Url::to(['site/about'])?>">About</a>
                  </li>
                </ul>
                <?=$this->render('/site/partials/site_search')?>
              </div>
            </nav>
        </header>
        <div class="wrapper">
            <div class="container-fluid content">
                <?=$content?>
            </div>
            <!--Footer-->
            <footer class="container-fluid">
                <div class="row justify-content-center bg-secondary text-white text-center">
                    <ul class="col-md-4 list-group list-group-flush">
                      <li class="list-group-item bg-secondary">Contact us:</li>
                      <li class="list-group-item bg-secondary">
                        <a href="mailto:#" class="text-white">mysite@test.com</a>
                      </li>
                      <li class="list-group-item bg-secondary">
                        <a href="tel:#" class="text-white">000-000-000</a>
                        </li>
                    </ul>
                    <ul class="col-md-4 list-group list-group-flush">
                      <li class="list-group-item bg-secondary">Friends:</li>
                      <li class="list-group-item bg-secondary">
                        <a href="#" class="text-white">www.somesite.com</a>
                      </li>
                      <li class="list-group-item bg-secondary">
                        <a href="#" class="text-white">www.anothersite.com</a>
                      </li>
                    </ul>
                </div>
            </footer>
        </div>
        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main_BAKUP.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>