controllers/SiteController.php
<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Article;
use app\models\Category;
use app\models\Tag;
use app\models\User;
use app\models\Comment;
use app\models\SiteSearch;
use yii\data\Pagination;

class SiteController extends Controller {

  public function behaviors() {
      return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['logout'],
              'rules' => [
                  [
                      'actions' => ['logout'],
                      'allow' => true,
                      'roles' => ['@'],
                  ],
              ],
          ],
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'logout' => ['post'],
              ],
          ],
      ];
  }
  /**
   * {@inheritdoc}
   */
  public function actions()
  {
      return [
          'error' => [
              'class' => 'yii\web\ErrorAction',
          ],
          'captcha' => [
              'class' => 'yii\captcha\CaptchaAction',
              'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
          ],
      ];
  }
  /**
   * Displays contact page.
   *
   * @return Response|string
   */
  public function actionContact()
  {
      $model = new ContactForm();
      if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
          Yii::$app->session->setFlash('contactFormSubmitted');

          return $this->refresh();
      }
      return $this->render('contact', [
          'model' => $model,
      ]);
  }

	public function actionAbout() {
    return $this->render('about');
  }

	public function actionIndex() {
    $itemsOnPage = 3;
    $data = Article::selectAll($itemsOnPage);
    $articles = $data['articles'];
    $pagination = $data['pagination'];
    $latest = Article::getLatest();
    $categories = Category::getAll();
    $tags = Tag::getAll();
    $authors = User::getAll();
    
		return $this->render('index', compact(
      'articles', 'pagination', 'latest',
      'categories', 'tags', 'authors'));
	}

  public function actionViewSingle($id) {
    $commentModel = new Comment;
    $itemsOnPage = 4;
    $article = Article::selectOne($id);
    $article->updateCounters(['viewed' => 1]);
    $latest = Article::getLatest();
    $categories = Category::getAll();
    $tags = Tag::getAll();
    $authors = User::getAll();
    $data = Comment::getAllForArticle($id, $itemsOnPage);
    $comments = $data['comments'];
    $pagination = $data['pagination'];

  	return $this->render('single', compact(
      'article', 'comments', 'pagination', 'latest',
      'categories', 'tags', 'authors', 'commentModel'));
  }

  public function actionComment($id) {
      $commentModel = new Comment($id);
      if ($commentModel->load(Yii::$app->request->post())
          && $commentModel->save()) {
          Yii::$app->session->setFlash('comment', 'Your comment was sent to server. It will appear here soon.');
          $this->redirect(['site/view-single', 'id' => $id]);
      }
  }

  public function actionCategory($id) {
    $itemsOnPage = 3;
    $latest = Article::getLatest();
    $categories = Category::getAll();
    $tags = Tag::getAll();
    $authors = User::getAll();
    $data = Category::getArticlesByCategory($id, $itemsOnPage);
    $articles = $data['articles'];
    $pagination = $data['pagination'];

  	return $this->render('result', compact(
      'articles', 'pagination', 'latest',
      'categories', 'tags', 'authors'));
  }

  public function actionTag($id) {
    $itemsOnPage = 3;
    $latest = Article::getLatest();
    $categories = Category::getAll();
    $tags = Tag::getAll();
    $authors = User::getAll();
    $data = Tag::getArticlesByTag($id, $itemsOnPage);
    $articles = $data['articles'];
    $pagination = $data['pagination'];

    return $this->render('result', compact(
      'articles', 'pagination', 'latest',
      'categories', 'tags', 'authors'));
  }

  public function actionSearch($searchQuery) {
      $limit = 10;
      $data = SiteSearch::search($searchQuery, $limit);
      $articles = $data['articles'];
      $users = $data['users'];
      $comments = $data['comments'];
      $latest = Article::getLatest();
      $categories = Category::getAll();
      $tags = Tag::getAll();
      $authors = User::getAll();

      return $this->render('search_result', compact(
        'articles', 'users', 'comments',
        'latest', 'categories', 'tags', 'authors'));
  }

  public function actionUserArticles($id) {
    $itemsOnPage = 3;
    $latest = Article::getLatest();
    $categories = Category::getAll();
    $tags = Tag::getAll();
    $authors = User::getAll();
    $data = User::getAllArticlesByUser($id, $itemsOnPage);
    $articles = $data['articles'];
    $pagination = $data['pagination'];
    
    return $this->render('result', compact(
      'latest', 'categories', 'tags',
      'authors', 'articles', 'pagination'));
  }

}

views/site/partials/comment_form.php
<!--Comment Form-->
<?php
	use yii\helpers\Html;
	use yii\bootstrap\ActiveForm;

	if (!Yii::$app->user->isGuest) {
		$form = ActiveForm::begin([
  		'id' => 'comment-form',
  		'action' => [
  			'site/comment',
  			'id' => $article->id
  		],
  		'options' => [
  			'class' => 'form-horizontal mb-3'
  		]
  	]);

  	echo $form->field($commentModel, 'text')
  		->textArea(['
  			placeholder' => 'Comment text...',
  			'rows' => 3,
  			'cols' => 6
  		])
  		->label('Leave your comment');

		echo Html::submitButton('Leave comment',
			['class' => 'btn btn-primary shadow']);

  	ActiveForm::end();
	}
?>

<?php if (Yii::$app->session->hasFlash('comment')):?>
	<div class="alert alert-success alert-dismissible col-12 mt-2" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<?php echo Yii::$app->session->getFlash('comment'); ?>
	</div>
<?php endif;?>

views/site/partials/sidebar.php
<?php
	use yii\helpers\Url;
  use yii\helpers\Html;
  use yii\helpers\StringHelper;
?>
<!--Latest-->
<div class="list-group mb-3 shadow sidebar__latest">
  <h5 class="list-group-item list-group-item-primary active">
      Latest
  </h5>
  <?php foreach ($latest as $item):?>
    <a href="<?=Url::to(['site/view-single', 'id' => $item['id']])?>" class="list-group-item list-group-item-action border-primary">
      <small><?=Html::encode($item['put_date'])?></small>
      <p class="mb-1">
        <?=StringHelper::truncate($item['content'], 100)?>
      </p>
    </a>
  <?php endforeach;?>
  <a href="#" class="list-group-item list-group-item-action text-center border-primary">
    More
  </a>
</div>
<!--Categories-->
<div class="list-group mb-3 shadow sidebar__categories">
  <h5 class="list-group-item list-group-item-primary active">
    Categories
  </h5>
  <?php foreach ($categories as $category):?>
    <a href="<?=Url::to(['site/category', 'id' => $category->id])?>" class="list-group-item list-group-item-action border-primary d-flex justify-content-between align-items-center">
      <span><?=Html::encode($category->title)?></span>
      <span class="badge badge-primary text-white">
        <?=$category->getArticlesCount()?>
      </span>
    </a>
  <?php endforeach;?>
</div>
<!--Authors-->
<div class="list-group mb-3 shadow sidebar__authors">
  <h5 class="list-group-item list-group-item-primary active">
      Authors
  </h5>
  <?php foreach ($authors as $author):?>
    <a href="<?=Url::to(['site/user-articles', 'id' => $author->id])?>" class="list-group-item list-group-item-action border-primary d-flex justify-content-between align-items-center p-2">
      <img src="<?=$author->getImage()?>" alt="" class="rounded">
      <span><?=Html::encode($author->name)?></span>
      <span class="badge badge-secondary">
        <?=$author->getArticlesCount()?>
      </span>
    </a>
  <?php endforeach;?>
  <a href="<?=Url::to(['admin/user/index'])?>" class="list-group-item list-group-item-action border-primary text-center">
    Show all
  </a>
</div>
<!--Tags-->
<div class="card border-primary shadow">
  <h5 class="card-header text-white bg-primary">
    Tags
  </h5>
  <div class="card-body">
    <?php foreach ($tags as $tag):?>
      <a href="<?=Url::to(['site/tag', 'id' => $tag->id])?>">
        <?=Html::encode($tag->title)?>
      </a>
    <?php endforeach;?>
  </div>
</div>

views/site/partials/site_search.php
<form action="/site/search" method="get" class="form-inline">
    <div class="input-group">
      <input name="searchQuery" class="form-control" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
          <button class="btn btn-outline-light" type="submit">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </div>
    </div>
</form>